### PR TITLE
Add with_module_name option to list_align

### PR DESCRIPTION
**Pull request by ruhatch**

### CODE REVIEW

**Comment by ruhatch** [comment]
@jaspervdj any chance of getting this merged in? We started using this as a default style at IOHK and it's causing some pain that it's not upstreamed! Thanks!

**Comment by jaspervdj** [comment]
@ruhatch LGTM, sorry for being unresponsive on this.  Would it be possible to add a test as well though, so I don't break this in the future?

**Comment by dnadales** [comment]
@jaspervdj I added tests for this new feature, and @ruhatch had a look at them and he approves.

Let me know whether this PR can be merged now. Thanks!

**Comment by jaspervdj** [comment]
Thank you, tests look very good!

**Comment by dnadales** [comment]
Thanks @jaspervdj . Any chances of having this in a release soon?

**Pull request merged**
