### PR TITLE
Add a set of default language extensions for parsing

### PR DESCRIPTION
**Pull request by siddharthist**
See the comments for a detailed explanation.

Fixes jaspervdj/stylish-haskell#117

### CODE REVIEW

**Comment by jaspervdj** [comment]
Looks good, thanks!

**Comment by siddharthist** [comment]
@jaspervdj Thanks for reviewing and merging :+1: naturally, as this bug is affecting me, I eagerly await the next release!

**Comment by jaspervdj** [comment]
I've now released `stylish-haskell-0.6.0.0` which contains this (among other things).

**Comment by siddharthist** [comment]
@jaspervdj Thanks! I'll update the NixOS package :-)

**Comment by jaspervdj** [comment]
@siddharthist I've removed `XmlSyntax` from the whitelisted extensions, it was causing parsing issues: #130

**Pull request merged**
