### PR TITLE
Bump aeson bound to < 1.6

### PR DESCRIPTION
**Pull request by bubba**

### CODE REVIEW

**Comment by bubba** [comment]
Argh looks like it's blocked by https://hackage.haskell.org/package/HsYAML-aeson

**Comment by EncodePanda** [comment]
> Argh looks like it's blocked by https://hackage.haskell.org/package/HsYAML-aeson

we can try pushing pr to hsyaml

**Comment by bubba** [comment]
[Looks like someone already has](https://github.com/haskell-hvr/HsYAML-aeson/pull/6), I've pinged hvr so hopefully we'll get a revision or release soon

**Comment by EncodePanda** [comment]
👍

**Comment by bubba** [comment]
Looks like the CI is failing to download a stackage snapshot?

**Comment by bubba** [comment]
ping @EncodePanda

**Comment by bubba** [comment]
HSyaml has had a revision with the bounds on aeson bumped 🎉

**Pull request merged**
